update to 0.10.1
AnacondaRecipes/composeml-feedstock pull request #1
Opened 2023-11-01 08:45 UTC by M-Waszkiewicz-Anaconda

update composeml to 0.10.1 
 - [upstream](https://github.com/alteryx/compose/tree/v0.10.1)
- add private channel as there is cyclic dependency in tests

2023-11-02 13:49 UTC, JeanChristopheMorinPerso requested changes

2023-11-02 13:49 UTC, JeanChristopheMorinPerso commented on recipe/meta.yaml
> +  script: {{ PYTHON }} -m pip install --no-deps --no-build-isolation -vv .
```suggestion
  skip: true  # [py<38]
  script: {{ PYTHON }} -m pip install --no-deps --no-build-isolation -vv .
```

2023-11-02 13:49 UTC, JeanChristopheMorinPerso commented on recipe/meta.yaml
> +    - composeml
```suggestion
```

2023-11-02 13:49 UTC, JeanChristopheMorinPerso commented on recipe/meta.yaml
> +    - pytest -k "not ( test_search_offset_mix_5 or test_minimum_data_per_group[minimum_data1] or test_sorted_distribution or test_subscriptable_slices[True-offsets2] or test_subscriptable_slices[True
```suggestion
    - pytest --pyargs composeml -v -k "not ( test_search_offset_mix_5 or test_minimum_data_per_group[minimum_data1] or test_sorted_distribution or test_subscriptable_slices[True-offsets2] or test_subscriptable_slices[True-offsets3])"
```

2023-11-02 13:49 UTC, JeanChristopheMorinPerso commented on recipe/meta.yaml
> +    - pyarrow >=7.0.0
```suggestion
    - woodwork >=0.11.0
    - pyarrow >=3.0.0
```

2023-11-02 15:11 UTC, skupr-anaconda commented on recipe/meta.yaml
> +    - matplotlib >=3.3.3
```suggestion
    - matplotlib-base >=3.3.3
```

2023-11-02 16:08 UTC, skupr-anaconda commented
An error on `linux-s390x`:
```
conda.exceptions.ResolvePackageNotFound:
  - pyarrow[version='>=3.0.0']
```

An error on `osx-64`:
```
ChecksumMismatchError: Conda detected a mismatch between the expected content and downloaded content
for url 'https://conda.anaconda.org/marekw/osx-64/featuretools-1.28.0-py310h5e5eb69_0.conda'.
```

2023-11-03 13:38 UTC, skupr-anaconda approved these changes

2023-11-03 14:52 UTC, cbouss approved these changes
LGTM

2023-11-03 16:29 UTC, merged